### PR TITLE
Tests and fixes

### PR DESCRIPTION
**Pull request by Ryanthegiantlion**
Fixes for #125, #137 and #161 

Also added tests for all the above.

### CODE REVIEW

**Comment by daffl** [comment]
This looks great, thank you! I'll let @DesignByOnyx have a look and then we can get it out.

**Comment by DesignByOnyx** [comment]
This looks awesome. Thanks for taking the time to do this. I see no reason not to merge.

For the sake of discussion, by introducing dialect-specific tests we have legitimized dialect-specific code. I was previously trying to avoid this, but I now see a lot of value in having optimizations for different engines. We should eventually start running the tests against all dialects so that we can catch any discrepancies quickly. I will create a separate issue to track that. Thanks for getting it started for us @Ryanthegiantlion!

**Comment by daffl** [comment]
@DesignByOnyx, @Ryanthegiantlion already got you there. CI tests for SQLite, MySQL and Postgres have been added in #160

**Comment by daffl** [comment]
Released as v2.3.1

**Comment by DesignByOnyx** [comment]
Ah, I missed that PR for the dialect-specific tests. My bad.

**Pull request merged**
