### PR TITLE
Fixed return value of patch method for postgresql dialect

### PR DESCRIPTION
**Pull request by msimulcik**
### Fixed return value of patch method for postgresql dialect
- [x] Tell us about the problem your pull request is solving.
For the postgresql dialect, the patch method is returning an array even if an ID is specified. This pull request makes the patch behaviour consistent.
- [x] Are there any open issues that are related to this?
No
- [x] Is this PR dependent on PRs in other repos?
No

### CODE REVIEW

**Comment by daffl** [comment]
This seems to be passing but I'm not sure I understand why unless the tests are missing something.

**Comment by msimulcik** [comment]
Do tests cover dialect differences, because I can't find it? I can add failing test, but pls point me to a repo where it belongs. Is it [feathers-service-tests](https://github.com/feathersjs/feathers-service-tests)?

**Comment by daffl** [comment]
Oh sorry, I see this was in a dialect specific branch. What I mean is that this looks like it would be a breaking change for anybody who is using the Postgres dialect because you used to get `results[1]` back and now get `results[1][0]` right?

**Comment by msimulcik** [comment]
I think breaking change was introduced by #93 because original behaviour of patch was to return single result when `id` was specified. I noticed this when I updated feathers-sequelize because I'm using postgresql dialect.

**Comment by daffl** [comment]
This does look like the right fix, let's hope this works (@MichaelErmer sorry if we're breaking the build).

**Comment by msimulcik** [comment]
Thanks for merging it, but I still think we should add a test covering this dialect branch. I'm happy to do it, I just need to know where it belongs.

**Comment by daffl** [comment]
Good call, I haven't released it yet. We have to set up [PostgreSQL on Travis CI](https://docs.travis-ci.com/user/database-setup/#PostgreSQL) and then run the [base tests against that database](https://github.com/feathersjs/feathers-sequelize/blob/master/test/index.test.js#L96), probably by initializing a new sequelize and `app` with that connection.

**Comment by daffl** [comment]
I created follow-up issue #105

**Pull request merged**
