### PR TITLE
Adding ability to scope operations

### PR DESCRIPTION
**Pull request by bparise**
### Summary

Sequelize allows you to apply a scope() to certain operations [(Sequelize Scope Documentation)](http://docs.sequelizejs.com/manual/tutorial/scopes.html).

This PR adds the ability to set the scope for the operation.  This PR is linked to #130.

```javascript
app.service('users').find({
  sequelize: {
    scope: 'active'
  }
}).then(activeUsers => {
  /* ... */
});
```

### CODE REVIEW

**Comment by daffl** [comment]
PR looks great, thank you! If @DesignByOnyx gives his blessing I'll get it released as a minor version right away. Also, the documentation at https://docs.feathersjs.com/api/databases/sequelize.html should also be updated accordingly.

**Comment by daffl** [comment]
Released as v2.2.0, thank you! Don't forget to update the documentation accordingly otherwise nobody will know this features exists 😄

**Comment by EmirGluhbegovic** [comment]
Hey,

I want to use scope and am happy that this feature got merged but could someone please guide me as how to use this feature, I cannot seem to find any documentation for it?

**Comment by EmirGluhbegovic** [comment]
@DesignByOnyx How so? I believe the author of this pull request said he needed to add documentation but hasn't so far. I am willing to document my process just want to check if I am missing something. I did look at the pull request itself and looks like it cannot handle parameters with the scope (but i do stand to be corrected as I didnt take the closest look).
Thanks though

**Pull request merged**
