### PR TITLE
Options param support for create method

### PR DESCRIPTION
**Pull request by rafalszemraj**
Fix for #25

### CODE REVIEW

**Comment by ekryski** [comment]
Thanks @rafalszemraj. Ideally we'd want to test for this. Since this is a such a benign change I'll add it and we can go back an add a specific test for passing options to Sequelize.

**Comment by ekryski** [comment]
I've publish v1.1.3 that contains this fix.

**Comment by daffl** [comment]
I'm not sure if this is the best fix.There is a chance that you can mess directly with the database by passing arbitrary query parameters from the client.

Instead of using `params` directly it should probably use `params.sequelize` to set those options.

**Comment by rafalszemraj** [comment]
@daffl Probably you're right. The reason I wanted to have this was to be able to create records with [n:m association ](http://docs.sequelizejs.com/en/latest/docs/associations/#creating-elements-of-a-hasmany-or-belongstomany-association). I'm just starting with feathers and I can see that relation model form sequelize is not yet provided (maybe you do not have any plans to do so?). Anyway, starting this with change like this it's not best idea I guess - whole thing needs to be planned beforehand. I can leave without that, you can revert that if you do not feel this is right way to do it.

**Comment by ekryski** [comment]
Ah shit! I missed that. Good catch @daffl. I think we should roll this change back then. Looks like we are missing documentation on the `params.sequelize` object and we really need an example of showing many-to-many relationships.

**Comment by daffl** [comment]
No need to roll it back, this is a good fix. We just need to change https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L83-L89 to

```js
  create(data, params) {
    const options = params.sequelize || {};
    if (Array.isArray(data)) {
      return this.Model.bulkCreate(data, options).catch(utils.errorHandler);
    }

    return this.Model.create(data, options).catch(utils.errorHandler);
  }
```

Then one can set `params.sequelize` to whatever it needs to be e.g. in a `before` hook.

**Comment by ekryski** [comment]
Ah ok cool. I'll fix that right away and do a new patch release.

**Comment by daffl** [comment]
@rafalszemraj I hope that works for you as well and many thanks again for the PR!

**Comment by rafalszemraj** [comment]
:+1:

**Pull request merged**
